crowd_fund/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from crowd_fund import settings
from crowd_fund.views import render_home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/dj-rest-auth/token/verify/', ),
    path('projects/', include('projects.urls')),
    path('user/', include('crowd_fund_app.urls')),
    path('image/', include('images.urls')),
    path('', render_home, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
#
from django.urls import path

from images.images.views import display_image

urlpatterns = [
    # path('<image_name>/', display_image, name='display_image'),
    path('media/projects/images/<image_name>', display_image),
]

projects/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

from projects.projects.views import ProjectViewSet, DonationViewSet, donation_create, project_create, ProjectDelete, \
    project_update, comment_create, comment_report, rate_project, project_report, reply_create

app_name = 'projects'

urlpatterns = [
    path('<pk>', ProjectViewSet.as_view({'get': 'retrieve'}), name='project'),
    path('report/<project_id>', project_report, name='project_report'),
    path('delete/<pk>', ProjectDelete.as_view(), name='project_delete'),
    path('deleted_msg/', TemplateView.as_view(template_name='projects/project_deleted_msg.html'),
         name='project_deleted_msg'),
    path('update/<pk>', project_update, name='project_update'),
    path('donation_create/<proj_id>/<proj_title>', donation_create, name='donation_create'),
    path('donate/', DonationViewSet.as_view({'post': 'create'}), name='donate'),
    path('project_create/', project_create, name='project_create'),
    path('comment/', comment_create, name='comment_create'),
    path('comment/report/<comment_id>/', comment_report, name='comment_report'),
    path('reply/report/<comment_id>/<reply_id>/', comment_report, name='reply_report'),
    path('reply/', reply_create, name='reply_create'),
    path('rate/', rate_project, name='rate_project'),
    path('', ProjectViewSet.as_view({'get': 'list'}), name='projects'),
]

router = SimpleRouter()
router.register('', ProjectViewSet, basename="projects")
urlpatterns.extend(router.urls)

crowd_fund/views.py
from statistics import mean

from django.shortcuts import render

from projects.models import Project, FeaturedProject, ProjectCategory
from projects.projects.views import get_project_rates


def render_home(request):
    projects = list(Project.objects.all())
    top_rated = sorted(projects, key=lambda p: mean(get_project_rates(p)), reverse=True)
    latest = sorted(projects, key=lambda p: p.added_at, reverse=True)
    featured = FeaturedProject.objects.all()
    categories = ProjectCategory.objects.all()
    context = {
        'top_rated': top_rated[:5],
        'latest': latest[:5],
        'featured': featured[:5],
        'categories': categories,
    }
    # return render(request, 'projects/project_carousel.html', context)
    return render(request, 'home.html', context)

crowd_fund/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'crowd_fund_app/css/layout.css' %}"/>
    {% block links %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <h1>Welcome to Crowd-fund App</h1>
    <div style="background-color: lightgrey; ">
        <a href="{% url 'home' %}">Home</a>
        {% if request.user.id %}
        <a href="{% url 'user_logout' %}">Logout</a>
        <a href="{% url 'user_details' %}">My panel</a>
        <a href="{% url 'user_profile' %}">My profile</a>
        {% else %}
        <a href="{% url 'signup' %}">Signup</a>
        {% endif %}
        {% block header %}
        {% endblock %}
    </div>
</header>

<p>
<div class="row">
    <div class="left">
    {% block content %}
    {% endblock %}
    </div>
    <div class="right">
        {% if not request.user.id %}
            {% include "crowd_fund_app/login.html" %}
        {% endif %}
        <div style="padding: 5px; ">
        Navigate to:
        <ul>
            <li><a href="{% url 'projects:projects' %}">All Projects</a></li>
        </ul>
        </div>
        {% block right_panel %}
        {% endblock %}
    </div>
</div>
</p>

<footer style="background-color: lightgrey; ">
    Copyrights reserved 2022
</footer>
</body>
</html>

crowd_fund/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Crowd-fund app{% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'projects/css/carousel_layout.css' %}"/>
{% endblock %}
{% block header %}
<div class="welcome-msg">
    Welcome
    {% if request.user.id %}
        {{ request.user }}
    {% else %}
        guest
    {% endif %}
</div>
{% include "projects/projects_header.html" %}
{% endblock %}

{% block content %}
    <h3>Top projects:</h3>
    {% if top_rated %}
        <div class="center"><div style="width:60%; height:50%; ">{% include "projects/project_carousel.html" with top_rated=top_rated %}</div></div>
    {% else %}
        <p>No projects found</p>
    {% endif %}

    <h3>Latest projects:</h3>
    {% if latest %}
        <ul>
        {% for p in latest %}
            <li><a href="{% url 'projects:project' p.id %}">{{ p.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No projects found</p>
    {% endif %}

    <h3>Featured projects:</h3>
    {% if featured %}
        <ul>
        {% for p in featured %}
            <li><a href="{% url 'projects:project' p.project_id.id %}">{{ p.project_id.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No projects found</p>
    {% endif %}
{% endblock %}
{% block right_panel %}
<ul><li><a href="{% url 'projects:project_create' %}">Create project</a></li></ul>
{% endblock %}