crowd_fund/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from crowd_fund import settings
from crowd_fund.views import render_home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/dj-rest-auth/token/verify/', ),
    path('projects/', include('projects.urls')),
    path('user/', include('crowd_fund_app.urls')),
    path('image/', include('images.urls')),
    path('', render_home, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
#
from django.urls import path

from images.images.views import display_image

urlpatterns = [
    # path('<image_name>/', display_image, name='display_image'),
    path('media/projects/images/<image_name>', display_image),
]

projects/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

from projects.projects.views import ProjectViewSet, DonationViewSet, donation_create, project_create, ProjectDelete, \
    project_update, comment_create, comment_report, rate_project, project_report, reply_create

app_name = 'projects'

urlpatterns = [
    path('<pk>', ProjectViewSet.as_view({'get': 'retrieve'}), name='project'),
    path('report/<project_id>', project_report, name='project_report'),
    path('delete/<pk>', ProjectDelete.as_view(), name='project_delete'),
    path('deleted_msg/', TemplateView.as_view(template_name='projects/project_deleted_msg.html'),
         name='project_deleted_msg'),
    path('update/<pk>', project_update, name='project_update'),
    path('donation_create/<proj_id>/<proj_title>', donation_create, name='donation_create'),
    path('donate/', DonationViewSet.as_view({'post': 'create'}), name='donate'),
    path('project_create/', project_create, name='project_create'),
    path('comment/', comment_create, name='comment_create'),
    path('comment/report/<comment_id>/', comment_report, name='comment_report'),
    path('reply/report/<comment_id>/<reply_id>/', comment_report, name='reply_report'),
    path('reply/', reply_create, name='reply_create'),
    path('rate/', rate_project, name='rate_project'),
    path('', ProjectViewSet.as_view({'get': 'list'}), name='projects'),
]

router = SimpleRouter()
router.register('', ProjectViewSet, basename="projects")
urlpatterns.extend(router.urls)

projects/models.py
from django.db import models

from crowd_fund_app.models import CustomUser
from utils.validators import greater_than_zero_validator


class ProjectCategory(models.Model):
    name = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class ProjectTag(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class CommentReply(models.Model):
    reply = models.TextField(max_length=1024)
    comment_id = models.ForeignKey(to='ProjectComment', related_name='replies', on_delete=models.CASCADE)
    user_id = models.ForeignKey(to=CustomUser, related_name='replies', on_delete=models.CASCADE)

    def __str__(self):
        return self.reply


class ProjectComment(models.Model):
    comment = models.TextField(max_length=1024)
    project_id = models.ForeignKey(to='Project', related_name='comments', on_delete=models.CASCADE)
    user_id = models.ForeignKey(to=CustomUser, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.comment


class Project(models.Model):
    title = models.CharField(max_length=64, null=False)
    details = models.TextField(max_length=1024)
    category = models.ForeignKey(to=ProjectCategory, related_name='projects', on_delete=models.SET_NULL, null=True)
    user_id = models.ForeignKey(to=CustomUser, related_name='projects', on_delete=models.CASCADE)
    total_target = models.FloatField(null=False, validators=[greater_than_zero_validator])
    tags = models.ManyToManyField(to=ProjectTag, related_name='projects')
    start_date = models.DateField(null=False)
    end_date = models.DateField(null=False)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProjectRate(models.Model):
    class Choices(models.IntegerChoices):
        Poor = 0
        Acceptable = 1
        Good = 2
        Viable = 3
        Promising = 4
        Wonderful = 5

    @classmethod
    def get_rate_title(cls, rate):
        return cls.Choices.choices[rate]

    @classmethod
    def get_rate_titles(cls):
        return cls.Choices.choices

    rate = models.IntegerField(choices=Choices.choices)
    project_id = models.ForeignKey(Project, models.CASCADE, related_name='rates')
    user_id = models.ForeignKey(CustomUser, models.CASCADE, related_name='rates')


class FeaturedProject(models.Model):
    project_id = models.OneToOneField(Project, models.CASCADE)


    def __str__(self):
        return self.project_id.title


class Donation(models.Model):
    user_id = models.ForeignKey(to=CustomUser, related_name='donations', on_delete=models.CASCADE)
    project_id = models.ForeignKey(to=Project, related_name='donations', on_delete=models.CASCADE)
    amount = models.FloatField(null=False, validators=[greater_than_zero_validator])
    date = models.DateTimeField(auto_now_add=True)

projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    images = forms.ImageField()

    class Meta:
        model = Project
        fields = ("title", "details", "category", "total_target", "tags", "start_date", "end_date", "images")

projects/projects/views.py
import os
from itertools import count, chain
from statistics import mean, StatisticsError

from allauth.account.adapter import DefaultAccountAdapter
from allauth.utils import build_absolute_uri
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DeleteView
from rest_framework import viewsets

from crowd_fund_app.models import CustomUser
from images.models import ProjectImage
from projects.models import Project, ProjectCategory, ProjectTag, Donation, ProjectComment, ProjectRate, CommentReply
from projects.serializers import ProjectSerializer, DonationSerializer


def reply_create(request):
    user = request.user
    comment_id = request.POST['comment_id']
    comment = ProjectComment.objects.get(pk=comment_id)
    CommentReply.objects.create(reply=request.POST['reply'], comment_id=comment, user_id=user)
    project_id = request.POST.get('project_id')
    return redirect(reverse('projects:project', args=(project_id, )))


class ReportAdapter(DefaultAccountAdapter):
    def get_email_confirmation_redirect_url(self, request):
        return HttpResponse('Your report was sent to site admins')


def comment_report(request, comment_id, reply_id=None):
    user = request.user
    if user.id is None:
        return HttpResponse("You must be logged in", status=400)

    comment = ProjectComment.objects.get(id=comment_id)
    reply = CommentReply.objects.get(id=reply_id) if reply_id else None

    project = Project.objects.get(id=comment.project_id.id)
    current_site = get_current_site(request)
    staff = CustomUser.objects.filter(is_staff=True)
    for admin_user in staff:
        email = admin_user.email
        path = reverse('projects:project', args=(comment.project_id.id,))
        url = build_absolute_uri(request, path)
        context = {
            'current_site': current_site,
            'username': user.username,
            'project_title': project.title,
            'comment_id': comment_id,
            'comment': comment,
            'reply_id': reply_id,
            'reply': reply,
            'url': url,
            'request': request,
        }
        adapter = ReportAdapter(request)
        template_prefix = 'comments/reply_report' if reply_id else 'comments/comment_report'
        adapter.send_mail(template_prefix, email, context)

    return render(request, 'comments/comment_reported.html',
                  context={'url': reverse('projects:project', args=(project.id,))})


def project_report(request, project_id):
    user = request.user
    if user.id is None:
        return HttpResponse("You must be logged in", status=400)

    project = Project.objects.get(id=project_id)
    current_site = get_current_site(request)
    staff = CustomUser.objects.filter(is_staff=True)
    for admin_user in staff:
        email = admin_user.email
        path = reverse('projects:project', args=(project_id,))
        url = build_absolute_uri(request, path)
        context = {
            'current_site': current_site,
            'username': user.username,
            'project_title': project.title,
            'url': url,
            'request': request,
        }
        adapter = ReportAdapter(request)
        adapter.send_mail('projects/project_report', email, context)

    return render(request, 'projects/project_reported.html',
                  context={'url': reverse('projects:project', args=(project.id,))})


def rate_project(request):
    project_id = request.POST['project_id']
    if int(request.POST['rate']) < 0 or int(request.POST['rate']) > 5:
        return redirect(reverse('projects:project', args=(project_id,)))
    user_id = request.user
    if user_id == Project.objects.get(id=project_id).id:
        print('own')
    try:
        project_rate = ProjectRate.objects.get(Q(user_id__id=request.user.id) & Q(project_id__id=project_id))
    except:
        project_rate = None

    if project_rate:
        project_rate.rate = request.POST['rate']
        project_rate.save()
    else:
        project = Project.objects.get(pk=project_id)
        ProjectRate.objects.create(rate=request.POST['rate'], project_id=project, user_id=user_id)
    user_rate = request.POST['rate']
    return redirect(reverse('projects:project', args=(project_id, )))


def comment_create(request):
    user_id = request.user
    project_id = request.POST['project_id']
    project = Project.objects.get(pk=project_id)
    ProjectComment.objects.create(comment=request.POST['comment'], project_id=project, user_id=user_id)
    return redirect(reverse('projects:project', args=(project_id, )))


class ProjectDelete(DeleteView):
    model = Project
    success_url = '/projects/deleted_msg/'

    def form_valid(self, form):
        for image in ProjectImage.objects.filter(project_id__id=self.object.id):
            image.delete()
        return super().form_valid(self.get_form())


def project_update(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        category_id = request.POST.get('category', None)
        tags = []
        if request.POST.get('tags'):
            for tag in request.POST.getlist('tags'):
                tags.append(ProjectTag.objects.get(id=tag))
        project.title = request.POST.get('title')
        project.details = request.POST.get('details')
        project.category = ProjectCategory.objects.get(id=category_id)
        project.total_target = request.POST.get('total_target')
        project.start_date = request.POST.get('start_date')
        project.end_date = request.POST.get('end_date')
        project.user_id = request.user
        project.tags.set(tags)
        images = request.FILES.getlist('images')
        if images:
            project.images.set([])
            for image in project.images.all():
                if image not in images:
                    image.delete()
            for image in images:
                ProjectImage.objects.create(image=image, project_id=project)
        project.save()
        return render(request, template_name="projects/project_updated_msg.html", context={'project_id': project.id})
    else:
        project_tag_ids = [tag_id['id'] for tag_id in project.tags.all().values('id')]
        str(project.start_date)
        return render(request, 'projects/project_update.html',
                      context={'categories': ProjectCategory.objects.all(),
                               'tags': ProjectTag.objects.all(),
                               'project': project,
                               'project_tag_ids': project_tag_ids,
                               'start_date': str(project.start_date),
                               'end_date': str(project.end_date)})


def project_create(request):
    if request.method == 'POST':
        category = request.POST.get('category')
        tags = []
        if request.POST.get('tags'):
            for tag in request.POST.getlist('tags'):
                tags.append(ProjectTag.objects.get(id=tag))
        project = Project.objects.create(
            title=request.POST.get('title'),
            details=request.POST.get('details'),
            category=ProjectCategory.objects.get(id=category),
            total_target=request.POST.get('total_target'),
            start_date=request.POST.get('start_date'),
            end_date=request.POST.get('end_date'),
            user_id=request.user,
        )
        project.tags.set(tags)
        images = request.FILES.getlist('images')
        for image in images:
            ProjectImage.objects.create(image=image, project_id=project)
        return render(request, template_name="projects/project_created_msg.html")
    else:
        return render(request, 'projects/project_create.html',
                      context={'categories': ProjectCategory.objects.all(),
                               'tags': ProjectTag.objects.all()})


def get_project_rates(project):
    rates = [r[0] for r in project.rates.values_list('rate')]
    return rates if rates else [0]


class ProjectViewSet(viewsets.ModelViewSet):
    serializer_class = ProjectSerializer

    # permission_classes = [permissions.IsAuthenticated, OwnBookPermission]

    def get_queryset(self):
        # return Project.objects.filter(user_id__id=self.request.user.id)
        # print(self.request.query_params['category'])
        category = self.request.query_params.get('category', None)
        if category and category != "-1":
            response = Project.objects.filter(category=category)
        else:
            response = Project.objects.all()
        search_string = self.request.query_params.get('search_string', None)
        if search_string:
            search_by = self.request.query_params.get('search_by', None)
            if search_by == 'title':
                response = response.filter(title__icontains=search_string)
            elif search_by == 'tag':
                tags = ProjectTag.objects.filter(name__icontains=search_string)
                response = list(response.filter(tags__in=tags))
            else:
                tags = list(ProjectTag.objects.filter(name__icontains=search_string))
                response = set(chain(response.filter(title__icontains=search_string), response.filter(tags__in=tags)))
        return response

    def list(self, request, *args, **kwargs):
        response = super().list(request.data, args, kwargs)

        for project_data in response.data:
            rates = ProjectRate.objects.filter(id__in=project_data['rates']).values('rate').values('rate')
            rates = map(lambda x: x['rate'], rates)
            try:
                project_data['rate'] = mean(rates)
            except StatisticsError:
                project_data['rate'] = 0
            project_data['category'] = ProjectCategory.objects.get(pk=project_data['category'])

projects/templates/projects/donation_create.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Donate{% endblock %}
{% block content %}
<h2>Donate to Project: {{ proj_title }}</h2>
<form action="{% url 'projects:donate'%}" method="post">
    {%csrf_token%}
    <label for="amount">Amount:</label>
    <input type="text" id="amount" name="amount"><br>
    <input type="hidden" name="project_id" value="{{ proj_id }}">
    <input type="hidden" name="user_id" value="{{ user.id }}">
    <input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/donation_created_msg.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project created{% endblock %}
{% block content %}
<p>Thank you for your donation</p>
<p><a href="{% url 'projects:project' project_id %}">Back</a></P>
{% endblock %}

projects/templates/projects/filter_box.html
<form method="get" action="{% url 'projects:projects'%}">
    <label for="category">Fundraise for category:</label>
    <select id="category" name="category">
        <option value="-1" selected="selected">All</option>
        {% for category in categories %}
            <option value="{{ category.id }}"
                    {% if category_displayed == category.id %}selected="selected"{% endif %}> {{ category.name }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>

projects/templates/projects/project_base.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'projects/css/project_layout.css' %}"/>
{% block project_links %}
{% endblock %}
{% endblock %}
{% block header %}
{% include 'projects/projects_header.html' %}
{% endblock %}
{% block content %}
{% block project_content %}
{% endblock %}
{% endblock %}

projects/templates/projects/project_carousel.html
<div class="slideshow-container">
{% for p in top_rated %}
  <a href="{% url 'projects:project' p.id %}">
    <div class="mySlides fade">
      <div class="numbertext">{{ forloop.counter }} / {{ top_rated|length }}</div>
      <img src="{{MEDIA_URL}}{{ p.images.all.first }}" style="width:100%">
      <div class="text">{{ p.title }}</div>
    </div>
  </a>
{% endfor %}
<a class="prev" onclick="plusSlides(-1)">❮</a>
<a class="next" onclick="plusSlides(1)">❯</a>

</div>
<br>

<div style="text-align:center">
  {% for p in top_rated %}
    <span class="dot" onclick="currentSlide({{ forloop.counter }})"></span>
  {% endfor %}
</div>

<script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>

projects/templates/projects/project_confirm_delete.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project created{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1>Are you sure you want to delete Project: {{ object }}?</h1>
    <input type="submit" value="Delete">
</form>
<p><a href="{% url 'projects:project' project.id %}">Back</a></P>
{% endblock %}

projects/templates/projects/project_create.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Create a project{% endblock %}
{% block content %}
<h2>Please, enter project details</h2>
<form action="{% url 'projects:project_create'%}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <table>
        <tr>
            <td><label for="title">Title:</label></td>
            <td><input type="text" id="title" name="title"></td>
        </tr>
        <tr>
            <td><label for="details">Details:</label></td>
            <td><textarea id="details" name="details" rows="4" cols="50"></textarea></td>
        </tr>
        <tr>
            <td><label for="category">Category:</label><br></td>
            <td>
                <select name="category" id="category">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
            </td>
        </tr>
       <tr>
           <td><label for="total_target">Total target:</label></td>
           <td><input type="text" id="total_target" name="total_target"><br></td>
       </tr>
        <tr>
            <td><label for="tags">Tags:</label><br></td>
            <td><select name="tags" id="tags" multiple>
            {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag.name }}</option>
            {% endfor %}
        </select></td>
        </tr>
        <tr>
            <td><label for="start_date">Start date:</label></td>
            <td><input type="date" id="start_date" name="start_date"><br></td>
        </tr>
        <tr>
            <td><label for="end_date">End date:</label></td>
            <td><input type="date" id="end_date" name="end_date"><br></td>
        </tr>
        <tr>
            <td><label for="images">Images:</label><br></td>
            <td><input type="file" id="images" name="images" multiple></td>
        </tr>
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/project_created_msg.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project created{% endblock %}
{% block content %}
<p>Project created successfully</p>
<p><a href="{% url 'user_details' %}">Back</a></P>
{% endblock %}

projects/templates/projects/project_deleted_msg.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project created{% endblock %}
{% block content %}
<p>Project deleted successfully</p>
<p><a href="{% url 'user_details' %}">Back to Home</a></P>
{% endblock %}

projects/templates/projects/project_details.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project: {{ title }}{% endblock %}
{% block project_links %}
    <link rel="stylesheet" href="{% static 'projects/css/carousel_layout.css' %}"/>
{% endblock %}
{% block project_content %}
<h2 style="font: Arial; color: darkblue; text-align: center; ">{{ title }}</h2>
Created by: <a href="{% url 'user_public_profile' user.id %}">{{ user.username }}</a>
<p>
    {% if request.user.id %}
        {% if request.user.id == user_id %}
            {% if percent_target < 25 %}
                <span> <a href="{% url 'projects:project_delete' id %}">Delete</a></span>
                </script>
            {% endif %}
            <span> <a href="{% url 'projects:project_update' id %}">Edit</a></span>
        {% else %}
            <span><a href="{% url 'projects:donation_create' id title %}">Donate</a></span>
            <span><a href="{% url 'projects:project_report' id %}">Report</a></span>
        {% endif %}
    {% endif %}
</p>

{% if request.user.id is not None and request.user.id != user_id %}
    <form method="post" action="{% url 'projects:rate_project' %}">
    {%csrf_token%}
    <input type="hidden" name="project_id" value="{{ id }}">
    <label for="rate">Your rating:</label>
    <select name="rate" id="rate">
        <option value="-1" selected="selected"></option>
        {% for rate_item in rate_items %}
            <option value="{{ rate_item.0 }}"
                    {% if user_rate == rate_item.0 %}selected="selected"{% endif %}>{{ rate_item.1 }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Submit">
</form>
{% endif %}
<p>
    <table>
        <tr>
            <td>Overall Rating: </td>
            {% for i in "x"|ljust:"5" %}
                {% if forloop.counter0 < rate %}
                    <td style="border:1px solid red; background: red; width:10px; height:10px; "></td>
                {% else %}
                    <td style="border:1px solid red; width:10px; height:10px; "></td>
                {% endif %}
            {% endfor %}
        </tr>
    </table>
</p>

<div class="center"><div>{% include "projects/project_image_carousel.html" with images=images %}</div></div>

<table>
    {# <tr><td style="width:15%;">Title</td><td style="padding-right:15px; ">{{ title }}</td></tr> #}
    <tr><td>Category</td><td style="padding-right:15px; ">{{ category }}</td></tr>
    <tr><td>Total target</td><td style="padding-right:15px; ">L.E. {{ total_target }}</td></tr>
    <tr><td>Tags</td><td style="padding-right:15px; ">
        {% for tag in tags %}
        <span class="tag_cell">{{ tag.name }}</span>
        {% endfor %}
    </td></tr>
    <tr><td>Start date</td><td style="padding-right:15px; ">{{ start_date }}</td></tr>
    <tr><td>End date</td><td style="padding-right:15px; ">{{ end_date }}</td></tr>
    <tr><td>Added at</td><td style="padding-right:15px; ">{{ added_at }}</td></tr>
    <tr><td>Details: </td><td style="padding-right:15px;border: 1px solid black; ">{{ details }}</td></tr>
    <tr><td>Target percent: </td><td>{{ percent_target }} %</td></tr>
</table>
<h3>Comments</h3>
<p>
{% if comments %}
    {% for comment in comments %}
        <table width="50%">
            <tr>
                <td style="border: 1px solid black; width=50%; background-color: beige; ">
                    <a href="{% url 'user_public_profile' comment.user_id.id %}">{{ comment.user_id.username }}</a>
                    <div>
                        {% if request.user.is_staff %}
                            (id:{{ comment.id }})
                        {% endif %}
                        <a id="comment{{comment.id}}"></a>
                        {{ comment }}
                    </div>
                    <div>
                        <span>
                            <a href="javascript: void(0)" onclick="document.getElementById('replyField{{forloop.counter0}}').style.display = 'block';">Reply</a>
                            <span><a href="{% url 'projects:comment_report' comment.id %}">Report</a></span>
                            <div id="replyField{{forloop.counter0}}" style="display:none;">
                                <form method="post" action="{% url 'projects:reply_create' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                    <input type="hidden" name="project_id" value="{{ id }}">
                                    <textarea id="textInput" name="reply" maxlength="400" rows="4" style="resize: none; width:100%; "></textarea><br>
                                    <input type="submit">
                                </form>
                            </div>
                        </span>
                    </div>
                    {# Reply boxes #}
                    {% for reply in comment.replies.all %}
                    <div style="padding: 0 2px ;">
                        <table width="100%">
                            <tr>
                                <td style="border: 1px solid black; width=100%; background-color: white; ">
                                    <a href="{% url 'user_public_profile' reply.user_id.id %}">{{ reply.user_id.username }}</a>
                                    <div>
                                        {% if request.user.is_staff %}
                                            (id:{{ reply.id }})
                                        {% endif %}
                                        <a id="reply{{reply.id}}"></a>
                                        {{ reply }}
                                    </div>
                                    <div>
                                        <span><a href="{% url 'projects:reply_report' comment.id reply.id %}">Report</a></span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                {% endfor %}
                </td>
            </tr>
        </table>
    {% endfor %}
{% else %}
    <p>Be the first to comment</p>
{% endif %}
</p>
<form method="post" action="{% url 'projects:comment_create' %}">
    {%csrf_token%}
    <input type="hidden" name="project_id" value="{{ id }}">
    <label for="comment">Add comment:</label><br/>
    <textarea id="comment" name="comment" maxlength="400" rows="4" cols="53"></textarea><br/>
    <input type="submit" value="Submit">
</form>
{% endblock %}

{% block right_panel %}
{% if similar %}
<div style="padding: 5px; ">Similar projects:</div>
    <ul>
    {% for s in similar%}
        <li><a href="{% url 'projects:project' s.project.id %}">{{s.project.title}}</a></li>
    {% endfor %}
    </ul>
{% else %}
No similar projects found
{% endif %}
{% endblock %}

projects/templates/projects/project_reported.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Project reported{% endblock %}
{% block content %}
Thank you. Your report was sent to site admins
<p><a href="{{ url }}">Return to the project</a></p>
{% endblock %}

projects/templates/projects/project_update.html
{% extends 'projects/project_base.html' %}
{% load static %}

{% block title %}Update a project{% endblock %}
{% block content %}
{{project.start_date}}
<form action="{% url 'projects:project_update' project.id %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <table>
        <tr>
            <td><label for="title">Title:</label></td>
            <td><input type="text" id="title" name="title" value="{{ project.title }}"></td>
        </tr>
        <tr>
            <td><label for="details">Details:</label></td>
            <td><textarea id="details" name="details" rows="4" cols="50">{{ project.details }}</textarea></td>
        </tr>
        <tr>
            <td><label for="category">Category:</label></td>
            <td>
                <select name="category" id="category" value="">
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if category == project.category %}selected{% endif %}>{{ category.name }}</option>
                {% endfor %}
        </select>
            </td>
        </tr>
       <tr>
           <td><label for="total_target">Total target:</label></td>
           <td><input type="text" id="total_target" name="total_target" value="{{ project.total_target }}"></td>
       </tr>
        <tr>
            <td><label for="tags">Tags:</label></td>
            <td><select name="tags" id="tags" multiple>
            {% for tag in tags %}
                <option value="{{ tag.id }}" {% if tag.id in project_tag_ids %}selected{% endif %}>{{ tag.name }}</option>
            {% endfor %}
        </select></td>
        </tr>
        <tr>
            <td><label for="start_date">Start date:</label></td>
            <td><input type="date" id="start_date" name="start_date" value="{{start_date}}"></td>
        </tr>
        <tr>
            <td><label for="end_date">End date:</label></td>
            <td><input type="date" id="end_date" name="end_date" value="{{ end_date }}"></td>
        </tr>
        <tr>
            <td><label for="images">Images:</label></td>
            <td><input type="file" id="images" name="images" multiple></td>
        </tr>
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}